# Generated by Django 3.2 on 2021-05-04 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('create_by', models.DateTimeField(auto_now_add=True)),
                ('update_by', models.DateTimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditeur', to=settings.AUTH_USER_MODEL)),
                ('Readers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relecteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('level_critical', models.CharField(choices=[('VL', 'Très faible'), ('L', 'Faible'), ('M', 'Moyen'), ('H', 'Fort')], max_length=2)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.audit')),
            ],
        ),
    ]
