# Generated by Django 3.2 on 2021-05-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20210504_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='update_by',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
