# Generated by Django 3.2 on 2021-05-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_audit_update_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='update_by',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
